# Generated by Django 2.1.7 on 2019-03-13 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('intekimdb', '0023_auto_20190313_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthday',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 13, 46, 42, 755855, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='award',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 13, 46, 42, 757842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Biography', 'Biography'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('Film Noir', 'Film Noir'), ('History', 'History'), ('Horror', 'Horror'), ('Music', 'Music'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Short', 'Short'), ('Sport', 'Sport'), ('Superhero', 'Superhero'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], default='Action', error_messages={'unique': 'This catagory is already exist.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 13, 13, 46, 42, 756335, tzinfo=utc)),
        ),
    ]
